### ISSUE TITLE
Not thread-safe code

### ISSUE THREAD

**Issue by GProst** [loadkpi/crawler_detect#20]
Hey!
Assigning `env` to instance variable is not thread-safe: https://github.com/loadkpi/crawler_detect/blob/9a1e3a5db421f949a9853d09234745523bd982d5/lib/rack/crawler_detect.rb#L19
It causes server to return responses for different requests

**Comment by pandaiolo** [comment]
Rel #19 :)

**Comment by loadkpi** [comment]
Thanks. Merged
